/**
 * pulseReport.js — builds a downloadable Markdown "Pulse Report" of the
 * learner's session: mastery map, progress deltas, misconceptions caught,
 * and AI-informed next steps. Pure function: fully unit-testable.
 */
import { overallPulse, fadingConcepts, weakestConcept } from "./knowledgeTracker.js";

const bar = (score) => {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled);
};

const deltaTag = (d) => (d > 0 ? `▲ +${d}` : d < 0 ? `▼ ${d}` : "—");

/**
 * @param {{subject:string, goal:string, name?:string}} profile
 * @param {Record<string,number>} mastery       current mastery map
 * @param {Record<string,number>} sessionStart  mastery at session start
 * @param {{misconceptions:string[], fragile:string[]}} signals
 * @returns {string} Markdown report
 */
export function buildPulseReport(profile, mastery, sessionStart = {}, signals = { misconceptions: [], fragile: [] }) {
  const pulse = overallPulse(mastery);
  const prev = overallPulse(sessionStart);
  const hadBaseline = Object.keys(sessionStart).length > 0;
  const fading = fadingConcepts(mastery);
  const weakest = weakestConcept(mastery);
  const uniqueFragile = [...new Set(signals.fragile)];

  const lines = [
    `# LearnPulse — Pulse Report`,
    ``,
    `**Learner:** ${profile.name || "Anonymous"}`,
    `**Subject:** ${profile.subject}`,
    `**Goal:** ${profile.goal || "Just curious"}`,
    `**Overall pulse:** ${pulse}%${hadBaseline ? ` (session: ${prev}% → ${pulse}% ${deltaTag(pulse - prev)})` : ""}`,
    ``,
    `## Concept mastery`,
    ``,
  ];

  for (const [concept, score] of Object.entries(mastery).sort((a, b) => b[1] - a[1])) {
    const d = hadBaseline ? score - (sessionStart[concept] ?? 30) : 0;
    lines.push(
      `- **${concept}** \`${bar(score)}\` ${score}%` +
        (hadBaseline && d !== 0 ? ` (${deltaTag(d)})` : "") +
        (fading.includes(concept) ? ` · fading — review soon` : "")
    );
  }

  if (signals.misconceptions.length) {
    lines.push(``, `## Misconceptions caught & corrected`, ``);
    for (const m of [...new Set(signals.misconceptions)]) lines.push(`- ${m}`);
  }

  if (uniqueFragile.length) {
    lines.push(``, `## Fragile knowledge (right answers, low confidence)`, ``);
    for (const f of uniqueFragile) lines.push(`- ${f} — scheduled for review`);
  }

  lines.push(``, `## Recommended next steps`, ``);
  if (weakest) lines.push(`1. Target your weakest concept: **${weakest}** (${mastery[weakest]}%).`);
  if (fading.length) lines.push(`${weakest ? 2 : 1}. Revive fading concepts: ${fading.join(", ")}.`);
  lines.push(`${1 + (weakest ? 1 : 0) + (fading.length ? 1 : 0)}. Confirm mastery with Teach-Back once a concept passes 70%.`);
  lines.push(``, `_Generated by LearnPulse — learning that adapts to your pulse._`);

  return lines.join("\n");
}

/**
 * Same report, as print-ready HTML — used for the "Save as PDF" button
 * (opened in a new window and sent to window.print(), so the learner
 * picks "Save as PDF" as the destination). No PDF library needed.
 * @returns {string} HTML document
 */
export function buildPulseReportHtml(profile, mastery, sessionStart = {}, signals = { misconceptions: [], fragile: [] }) {
  const pulse = overallPulse(mastery);
  const prev = overallPulse(sessionStart);
  const hadBaseline = Object.keys(sessionStart).length > 0;
  const fading = fadingConcepts(mastery);
  const weakest = weakestConcept(mastery);
  const uniqueFragile = [...new Set(signals.fragile)];

  const rows = Object.entries(mastery)
    .sort((a, b) => b[1] - a[1])
    .map(([concept, score]) => {
      const d = hadBaseline ? score - (sessionStart[concept] ?? 30) : 0;
      const deltaHtml = hadBaseline && d !== 0 ? ` <span style="color:${d > 0 ? "#12b886" : "#e4573d"}">(${deltaTag(d)})</span>` : "";
      const fadingHtml = fading.includes(concept) ? ' <span style="color:#e8a13c">· fading, review soon</span>' : "";
      return `<li><strong>${concept}</strong> — ${score}%${deltaHtml}${fadingHtml}
        <div style="background:#d3f2e7;border-radius:99px;height:8px;margin:4px 0 10px;overflow:hidden;">
          <div style="background:#12b886;height:100%;width:${score}%;"></div>
        </div></li>`;
    })
    .join("");

  const misconceptionsHtml = signals.misconceptions.length
    ? `<h3>Misconceptions caught & corrected</h3><ul>${[...new Set(signals.misconceptions)].map((m) => `<li>${m}</li>`).join("")}</ul>`
    : "";
  const fragileHtml = uniqueFragile.length
    ? `<h3>Fragile knowledge (right answers, low confidence)</h3><ul>${uniqueFragile.map((f) => `<li>${f} — scheduled for review</li>`).join("")}</ul>`
    : "";

  const nextSteps = [];
  if (weakest) nextSteps.push(`Target your weakest concept: <strong>${weakest}</strong> (${mastery[weakest]}%).`);
  if (fading.length) nextSteps.push(`Revive fading concepts: ${fading.join(", ")}.`);
  nextSteps.push(`Confirm mastery with Teach-Back once a concept passes 70%.`);

  return `<html><head><title>LearnPulse Report — ${profile.subject}</title>
    <style>
      body{font-family:Georgia,serif;max-width:640px;margin:40px auto;color:#10312e;line-height:1.6;}
      h1{font-family:sans-serif;} h3{font-family:sans-serif;margin-top:24px;}
      .meta{color:#5a7370;} ul{padding-left:20px;} li{margin-bottom:4px;}
      .pulse{font-family:monospace;font-size:22px;color:#12b886;}
    </style></head><body>
    <h1>LearnPulse — Pulse Report</h1>
    <p class="meta">Learner: ${profile.name || "Anonymous"} · Subject: ${profile.subject} · Goal: ${profile.goal || "Just curious"}</p>
    <p class="pulse">${pulse}% overall${hadBaseline ? ` (session: ${prev}% → ${pulse}% ${deltaTag(pulse - prev)})` : ""}</p>
    <h3>Concept mastery</h3>
    <ul>${rows}</ul>
    ${misconceptionsHtml}
    ${fragileHtml}
    <h3>Recommended next steps</h3>
    <ol>${nextSteps.map((s) => `<li>${s}</li>`).join("")}</ol>
    <p class="meta"><em>Generated by LearnPulse — learning that adapts to your pulse.</em></p>
    </body></html>`;
}
