/**
 * pulseReport.js — builds a downloadable Markdown "Pulse Report" of the
 * learner's session: mastery map, progress deltas, misconceptions caught,
 * and AI-informed next steps. Pure function: fully unit-testable.
 */
import { overallPulse, fadingConcepts, weakestConcept } from "./knowledgeTracker.js";

const bar = (score) => {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled);
};

const deltaTag = (d) => (d > 0 ? `▲ +${d}` : d < 0 ? `▼ ${d}` : "—");

/**
 * @param {{subject:string, goal:string, name?:string}} profile
 * @param {Record<string,number>} mastery       current mastery map
 * @param {Record<string,number>} sessionStart  mastery at session start
 * @param {{misconceptions:string[], fragile:string[]}} signals
 * @returns {string} Markdown report
 */
export function buildPulseReport(profile, mastery, sessionStart = {}, signals = { misconceptions: [], fragile: [] }) {
  const pulse = overallPulse(mastery);
  const prev = overallPulse(sessionStart);
  const hadBaseline = Object.keys(sessionStart).length > 0;
  const fading = fadingConcepts(mastery);
  const weakest = weakestConcept(mastery);
  const uniqueFragile = [...new Set(signals.fragile)];

  const lines = [
    `# LearnPulse — Pulse Report`,
    ``,
    `**Learner:** ${profile.name || "Anonymous"}`,
    `**Subject:** ${profile.subject}`,
    `**Goal:** ${profile.goal || "Just curious"}`,
    `**Overall pulse:** ${pulse}%${hadBaseline ? ` (session: ${prev}% → ${pulse}% ${deltaTag(pulse - prev)})` : ""}`,
    ``,
    `## Concept mastery`,
    ``,
  ];

  for (const [concept, score] of Object.entries(mastery).sort((a, b) => b[1] - a[1])) {
    const d = hadBaseline ? score - (sessionStart[concept] ?? 30) : 0;
    lines.push(
      `- **${concept}** \`${bar(score)}\` ${score}%` +
        (hadBaseline && d !== 0 ? ` (${deltaTag(d)})` : "") +
        (fading.includes(concept) ? ` · fading — review soon` : "")
    );
  }

  if (signals.misconceptions.length) {
    lines.push(``, `## Misconceptions caught & corrected`, ``);
    for (const m of [...new Set(signals.misconceptions)]) lines.push(`- ${m}`);
  }

  if (uniqueFragile.length) {
    lines.push(``, `## Fragile knowledge (right answers, low confidence)`, ``);
    for (const f of uniqueFragile) lines.push(`- ${f} — scheduled for review`);
  }

  lines.push(``, `## Recommended next steps`, ``);
  if (weakest) lines.push(`1. Target your weakest concept: **${weakest}** (${mastery[weakest]}%).`);
  if (fading.length) lines.push(`${weakest ? 2 : 1}. Revive fading concepts: ${fading.join(", ")}.`);
  lines.push(`${1 + (weakest ? 1 : 0) + (fading.length ? 1 : 0)}. Confirm mastery with Teach-Back once a concept passes 70%.`);
  lines.push(``, `_Generated by LearnPulse — learning that adapts to your pulse._`);

  return lines.join("\n");
}
